# Generated by Django 4.0 on 2022-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/images')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('max_participant', models.DecimalField(decimal_places=0, max_digits=3)),
                ('activity_type', models.CharField(choices=[('FCFS', 'FirstComeFirstServe'), ('C', 'Candidate')], max_length=4)),
                ('register_time_start', models.CharField(max_length=150)),
                ('register_time_end', models.CharField(max_length=150)),
                ('activity_time_start', models.CharField(max_length=150)),
                ('activity_time_end', models.CharField(max_length=150)),
                ('user_list', models.ManyToManyField(blank=True, to='activities.UserList')),
            ],
        ),
    ]
